### ISSUE TITLE
'People', 'unpack', 'pack', 'fuel' and 'fly' are not working.

### ISSUE THREAD

**Issue by NoNamerCraft** [Alpel99/skyrama#1]
'People', 'unpack', 'pack', 'fuel' and 'fly' are not working.
Templates arent getting recognised. I tried changing the trsh but still does nothing.

Its wierd that 'arrow' does work even though it has the same resolution png and trsh as the ones above

Anyone knows how to overcome this problem?

**Comment by Alpel99** [comment]
Isn't the browser part of this game deactivated, how is this still usable?^^
Possible reasons/solutions:
#1 you are not on full-screen
#2 your monitor resolution differs from 1080p
#3 they changed their icons -> maybe you can try to take/cut screenshots yourself and replace the files with the same filename

**Comment by Alpel99** [comment]
Wasn't able to reproduce problems on multiple systems, keep me posted if there are more insights.
