### ISSUE TITLE
I can't click on the cookies button 

### ISSUE THREAD

**Issue by duckiquack** [Alpel99/skyrama#9]
It is quite literally that - it does not allow me to confirm the cookie usage on the website when i first launch the app, i can click as many times as i want and nothing happens ahahaha so i cant ever get past that screen

**Comment by Alpel99** [comment]
Hi, thank you for pointing this out. Normally there is a task to click the cookie accept button, but apparently that did not work, I will look into this, when there is time.
In the meantime, you could try this workaround:
* move the bot's browser as far up as possible
* move your taskbar away from the bottom
* there should be a few pixels of the blue button left to click

**Comment by duckiquack** [comment]
There indeed is that to accept the cookies but i simply cannot click it xD
Also, i can't resize the tab at all for whatever reason....

**Comment by Alpel99** [comment]
This is a little tricky, but no longer necessary.
d3a401c implements the click on the cookie accept button via javascript
That means no more potential problems with template matching
Update the bot in botfather and everything should work fine

**Comment by duckiquack** [comment]
![image](https://github.com/Alpel99/skyrama/assets/111783730/64513cbf-33c9-4d12-8662-b5d8b8c78fec)
![image](https://github.com/Alpel99/skyrama/assets/111783730/ef2104a0-e6d2-4c33-8f76-301498205cca)
Does nothing still tho...
